openapi:
  name: api-service-garbage
  title: Garbage
  version: '@project.version@'
spring:
  application:
    name: api-garbage
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 1.0
    enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: garbage-pool
    type: com.zaxxer.hikari.HikariDataSource
shedulers:
  update-garbage-schedules:
    cron: 0 0 5 * * MON-FRI
    shedlock-lock-at-most-for: PT2M