INSERT
    INTO
        garbageschedule(
            id,
            facilityCategory,
            additionalInformation,
            city,
            driveSchedule,
            houseNumber,
            postalCode,
            street,
            municipality_id,
            wasteType,
            nextPickupDate
        )
    VALUES(
        1,
        1,
        'A',
        'Sundsvall',
        'KP50TI2',
        '2',
        '85731',
        'Testgatan',
        '2281',
        'WASTE',
        '2026-03-31'
    );
