INSERT
    INTO
        garbageschedule(
            id,
            facilityCategory,
            additionalInformation,
            city,
            driveSchedule,
            houseNumber,
            postalCode,
            street,
            municipality_id,
            wasteType,
            nextPickupDate
        )
    VALUES(
        1,
        1,
        'A',
        'Sundsvall',
        'KP50TI2',
        '2',
        '85731',
        'Testgatan',
        '2281',
        'WASTE',
        '2026-03-31'
    ),
    (
        2,
        0,
        'A',
        'TESTSTAD',
        'KP10ON1',
        '5',
        '12345',
        'Storgatan',
        '2281',
        'WASTE',
        '2026-05-06'
    ),
    (
        3,
        0,
        'A',
        'TESTSTAD',
        'KP10ON1',
        '5',
        '12345',
        'Storgatan',
        '2281',
        'FOOD',
        '2026-05-06'
    ),
    (
        4,
        0,
        'G',
        'TESTSTAD',
        'KP10ON1',
        '5',
        '12345',
        'Storgatan',
        '2281',
        'WASTE',
        '2026-05-06'
    ),
    (
        5,
        0,
        'G',
        'TESTSTAD',
        'KP10ON1',
        '5',
        '12345',
        'Storgatan',
        '2281',
        'FOOD',
        '2026-05-06'
    );
